[package]
name = "tensor-amm"
version = "0.0.0"
edition = "2021"
readme = "README.md"
license-file = "../../LICENSE"

[features]
test-sbf = []
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
borsh = "^0.10"
num-derive = "^0.3"
num-traits = "^0.2"
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
solana-program = "< 1.18"
tensor_whitelist = { package = "tensor-whitelist", git = "ssh://git@github.com/tensor-foundation/whitelist.git" }
thiserror = "^1.0"

[dev-dependencies]
assert_matches = "1.5.0"
lazy_static = "1.4.0"
solana-program-test = ">1.14, < 1.18"
solana-sdk = "< 1.18"
spl-associated-token-account = "2"
